### PR TITLE
Websocket workaround while waiting for oficial WS support in SvelteKit

### PR DESCRIPTION
**Pull request by SrZorro**
[Sveltekit does not have yet support for websockets](https://github.com/sveltejs/kit/issues/1491).

I cannot wait for SvelteKit to implement native support for it as Im migrating a svelte + trpc + WS to SvelteKit with a deadline.

This pull request will implement a workaround to use websockets with `trpc-sveltekit` based on https://joyofcode.xyz/using-websockets-with-sveltekit until an oficial implementation for websockets exist.

**Status:** Experimental

- [x] Websocket works in development, with wroken hot reload
  - [x] Fix hot reload
- [x] Websocket works in production
- [x] Usage documentation
- [x] Workaround documentation
- [ ] Website docs

### CODE REVIEW

**Comment by icflorescu** [comment]
Nice!

Just a few observations:
- Make the websocket example run on a different port in dev mode; so far we have the docs on `3000`, `simple` on `3001` and `bookstall` on `3002`, so I'd suggest using `3003`.
- I think it would be a good idea to move `ws` from `dependencies` to `peerDependencies`. Most people won't use WS and we don't want WS being installed in their case. I'd also drop this line from `index.ts`: `export * as WS from "./websocket"` for the same reason. People who need to use WS would have to specifically import from `trpc-sveltekit/websocket` and make sure they add `ws` to their project deps.
- I'm not sure why, but there are some TS problems in `package/websocket/client.ts` and therefore running `yarn build` doesn't work.

**Comment by SrZorro** [comment]
Ty for the observations, my branch was a quick & dirty push I did 5 mins before leaving.
Its still In draft but next push will fix your observations 👌

**Comment by SrZorro** [comment]
Hi @icflorescu 

Its still missing documentation for the docs website but should be ready to review

**Comment by icflorescu** [comment]
Hey Fox! Thanks for the PR.
I've discovered there are still some hot-reloading-related issues, though.
When you modify `examples/websocket/src/routes/+page.svelte`, the browser doesn't pick up the changes and on subsequent WS calls (i.e. when clicking the Load button again) you're getting these messages in the console:

image

Then, after hard-reloading the page, loading data stops working.

Commenting out this function in `vitePlugin.ts` apparently fixes the issue:
```ts
  async handleHotUpdate() {
    // Close previous ws, we will create a new one
    // that server.createTRPCWebSocketServer will use
    // when called from hooks.server.ts
    await closeWSSGlobalInstance();
    createWSSGlobalInstance();
  },
```

Also, the changes to a tRPC route are not picked up.

**Comment by SrZorro** [comment]
I changed the hot reload implementation, now should work for the first call, consequent calls, svelte hot reloading and tRPC routes hot reloading

**Comment by SrZorro** [comment]
Hi @icflorescu 

I did some finishing touches and I tested it with the application I had to migrate, works like a charm in dev and prod.

Tell me if you find out anything more that needs fixing but should be ready to go

**Comment by icflorescu** [comment]
Thanks!

**Comment by Antonio-Bennett** [comment]
Funnily enough someone released this yesterday...https://www.npmjs.com/package/@carlosv2/adapter-node-ws maybe some ideas in there for improvement?

**Comment by SrZorro** [comment]
I saw yesterday that package, I checked the implementation and I find the one I implemented cleaner as It does not need another port in dev mode for the ws server, also mine does a lot of less "magic" to get the websocket server working

**Pull request merged**
